### ISSUE TITLE
Help on forecastClient.setAllowedHours

### ISSUE THREAD

**Issue by GnFlala** [ThingPulse/esp8266-weather-station#145]
Can someone help on how i can have the forecasts show days instead of specific hours of next days?

```
uint8_t allowedHours[] = {12};
    forecastClient.setAllowedHours(allowedHours, sizeof(allowedHours));
    forecastClient.updateForecasts(forecasts, OPEN_WEATHER_MAP_APP_ID, OPEN_WEATHER_MAP_LOCATION, MAX_FORECASTS);
```
This returns the forecast for next days for 14:00 if i am not wrong.

Changing allowedHours to 24 returns nothing.

Thanks in advance

**Comment by marcelstoer** [comment]
@bill-orange thanks

**Comment by twfry** [comment]
I also struggled with this and figured it out after a late night. Sharing here since this is the first page google lists. 

There are two key items:
1. allowedHours is in UTC time. 
2. Open weather map only returns forecasts in every 3 hour increments, i.e. it only returns values for 12am, 3am, 6am, 9am, 12pm, 3pm, 6pm, 9pm again in UTC time.

The way the library operates is it simply checks the allowedHours provided against the values Open weather map returns. This means the only valid values for allowedHours are { 0, 3, 6, 9, 12, 15, 18, 21 }. Any other values provided simply will not match any data returned. 

As a result you need to find the closest UTC time available to the local time you want and specify that in allowedHours. For example if you want values at 12am, 6am, 12pm, 6pm in local time and you are located in Eastern US time which is -5 from UTC, then setting "allowedHours = {18, 12, 6, 0};" will map to 1am, 7am, 1pm, 7pm EST which is the closest you can gather from the data returned. 

Hope this helps

**Comment by marcelstoer** [comment]
> It probably would be helpful to add an explanation in the comments where `allowedHours` is defined

When the need for a longish explanation for the user/developer arises I take it as a sign that my implementation probably isn't as good as it should be. Not saying this be easy, though. I see three issues with the current approach (apart from the fact that documentation is lacking):
- The variable/function could have a more expressive name. Which one? It's hard to deduce what "allowed hours" really means in the context of the library but this may be subjective.
- `allowedHours` being in UTC is not ideal. The library isn't fully timezone-aware and where it tries to be in the examples (e.g. https://github.com/ThingPulse/esp8266-weather-station/blob/master/examples/WeatherStationDemo/WeatherStationDemo.ino#L54-L55) it's overly simplistic. We have (open-source) applications that use this library which do have proper timezone support (-> https://github.com/ThingPulse/esp8266-weather-station-color/blob/master/settings.h#L75). However, if you configure a timezone for the application somewhere, it's certainly unexpected that not _all_ time-related operations or settings respect it.
- The library should hide that it actually only supports the 3h intervals {0, 3, ...} for `allowedHours`. It should treat this as an implementation limitation currently imposed by the use of the OpenWeatherMap API. Hence, it should allow you to set any 0-23 integer and automatically map it to the nearest forecast window.
