### ISSUE TITLE
Weatherstation Kit, connecting esp board to Arduino IDE, missing file.

### ISSUE THREAD

**Issue by ShadyShell1** [ThingPulse/esp8266-weather-station#193]
Hello everyone. 
I have some difficulty finding a file that connects my ESP board to Arduino IDE. The website that should have it, don't have it anymore. I think it's "USB to UART" or something like that. 

Anyone who can help me with this?

**Comment by marcelstoer** [comment]
I think what you need is this: https://docs.thingpulse.com/guides/iot-starter-kit/

More specifically maybe this: https://docs.thingpulse.com/how-tos/install-drivers/

**Comment by ShadyShell1** [comment]
No this is not what I need. I have checked this up and down!
I cannot find the file for connecting the ESP board to the Arduino IDE.

**Comment by CaptClaude** [comment]
You really haven't given anyone enough information to help.  
When you say you can't "connect the ESP board to the Arduino IDE", what is it that is not working? Do you see an error message?  Are you using a PC? Mac? Linux? Which ESP board are you using? Do you connect the ESP to your computer to the ESP via a USB cable? Knowing the answer to these questions will allow me/us to assist further.
For instance: I use a Mac and an ESP8266 "D1-Mini". It connects via USB cable.  When I first started programming D1-Minis, I needed to install a driver for the USB-serial chip that was on the board.  Since then, I have had zero issues.
