### ISSUE TITLE
The weather station shows a wrong moon phase

### ISSUE THREAD

**Issue by ZioJames** [ThingPulse/esp8266-weather-station#200]
### Expected behavior
The moon phase and age shown on the display should be consistent with actual lunar calendar.

### Actual behavior
I live near Florence, Italy: all regional settings has been edited accordingly.
Today, October 4th, according to moongiant.com website (and my calendar too!) the moon is still waning, with an illumination of about 5% and an age of 27.53 days. The weather station, on the contrary, already shows a new moon with illumination of 3% (that's almost right) and an age of 0.4 days.
I understand that a certain degree of approximation is unavoidable, but there seems to be an annoying two-day advance in calculation of moon age. The new moon will in fact be the 6th of October.
The date and time shown on the display are correct.

### Weather Station version
2.0.1 (latest)

### Hardware
Nodemcu ESP8266 Lolin v3 esp-12e Evaluation Board

**Comment by ZioJames** [comment]
Hi Marcel, thanks for your reply. Demo? What do you mean?

**Comment by marcelstoer** [comment]
I'm simply wondering what your sketch is and whether you use the simple `Astronomy` class or the more elaborate `SunMoonCalc` class. There are examples for both: https://github.com/ThingPulse/esp8266-weather-station/blob/master/examples/AstronomyDemo/AstronomyDemo.ino, https://github.com/ThingPulse/esp8266-weather-station/blob/master/examples/SunMoonCalcDemo/SunMoonCalcDemo.ino

**Comment by marcelstoer** [comment]
Maybe try the `SunMoonCalc` class instead as it's more elaborate. However, as disclosed in that class and in https://github.com/ThingPulse/esp8266-weather-station/blob/master/src/Astronomy.cpp all of those algorithms are not ours. We only ported existing code to Arduino/ESP8266.

> A better approximation (i.e. 29.53059...) of lunar month duration should not have any effect... right?

I don't think that's what you really meant 😜 It _should_ have an effect - more accurate results - otherwise improving it would be pointless, no?

Feel free to propose changes if you can confirm that they yield more accurate results, thanks.
